export enum KycStatus {
  NOT_STARTED = 'NOT_STARTED',
  DRAFT = 'DRAFT',
  PENDING_REVIEW = 'PENDING_REVIEW',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
  REQUIRES_ACTION = 'REQUIRES_ACTION',
  UNSUPPORTED = 'UNSUPPORTED',
}
