export enum KycProvider {
  FLUTTERWAVE = 'FLUTTERWAVE',
  LEAD_BANK = 'LEAD_BANK',
  SMILE_ID = 'SMILE_ID',
  VERTO = 'VERTO',
  ZERO_HASH = 'ZERO_HASH',
  COWRYWISE = 'COWRYWISE',
  APRIL = 'APRIL',
  COLUMN = 'COLUMN',
  ONESIGNAL = 'ONESIGNAL',
  SARDINE = 'SARDINE',
}
