export enum ProviderOperationType {
  RAIL_PROVISIONING = 'RAIL_PROVISIONING',
  CARD_TOPUP = 'CARD_TOPUP',
  CARD_FUNDING = 'CARD_FUNDING',
  EXTERNAL_TRANSFER = 'EXTERNAL_TRANSFER',
  INTERNAL_TRANSFER = 'INTERNAL_TRANSFER',
  WALLET_FUNDING = 'WALLET_FUNDING',
  FX_CONVERSION = 'FX_CONVERSION',
  KYC = 'KYC',
  AIRTIME = 'AIRTIME',
  DATA = 'DATA',
  UTILITY = 'UTILITY',
  NOTIFICATION = 'NOTIFICATION',
  CRYPTO = 'CRYPTO',
  INVESTMENT = 'INVESTMENT',
  FRAUD = 'FRAUD',
  LOAN = 'LOAN',
  TAX_FILING = 'TAX_FILING',
}

export enum ProviderOperationStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  REVERSED = 'REVERSED',
  UNDER_REVIEW = 'UNDER_REVIEW',
}

export enum ProviderWebhookEventStatus {
  RECEIVED = 'RECEIVED',
  PROCESSED = 'PROCESSED',
  FAILED = 'FAILED',
  IGNORED = 'IGNORED',
}
