"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = NonWinningNotification;
const jsx_runtime_1 = require("react/jsx-runtime");
const components_1 = require("@react-email/components");
const emailLayout_1 = require("../components/emailLayout");
const config_1 = require("../../src/utils/config");
function NonWinningNotification({ firstName, drawId }) {
    return ((0, jsx_runtime_1.jsxs)(components_1.Html, { children: [(0, jsx_runtime_1.jsx)(components_1.Preview, { children: "Better Luck Next Time with LottoNowNow!" }), (0, jsx_runtime_1.jsx)(components_1.Tailwind, { children: (0, jsx_runtime_1.jsx)(components_1.Body, { children: (0, jsx_runtime_1.jsx)(emailLayout_1.default, { children: (0, jsx_runtime_1.jsxs)(components_1.Row, { children: [(0, jsx_runtime_1.jsx)("h4", { className: "text-xl font-semibold", style: { fontSize: '25px' }, children: "LottoNowNow Results Update" }), (0, jsx_runtime_1.jsxs)(components_1.Text, { children: ["Hi ", firstName, ","] }), (0, jsx_runtime_1.jsx)(components_1.Text, { className: "text-justify", children: "We appreciate your participation in the latest LottoNowNow draw! While it was a close one, we regret to inform you that your ticket was not among the winning numbers this time." }), (0, jsx_runtime_1.jsx)(components_1.Text, { className: "text-justify", children: "But don\u2019t give up just yet! We have several exciting draws coming up, with more chances for you to win big. Join our current draws and increase your chances of becoming our next lucky winner!" }), (0, jsx_runtime_1.jsx)(components_1.Text, { className: "text-justify", children: "You can view the results of the latest draw and see if your numbers were close by visiting our website. Remember, every ticket is a step closer to winning, so keep trying!" }), (0, jsx_runtime_1.jsx)("a", { href: `${config_1.CONFIG_VARIABLES.APP_URL}/draws/${drawId}`, className: "text-center text-white bg-[#D3790D] text-2xl my-10 font-bold rounded-xl no-underline px-8 py-4", children: "VIEW DRAW RESULTS" }), (0, jsx_runtime_1.jsx)(components_1.Text, { className: "text-justify font-semibold", style: { marginTop: '15px' }, children: "Ready to take another shot? Visit our website to check out the ongoing draws and pick your next lucky numbers!" }), (0, jsx_runtime_1.jsxs)("h1", { className: "text-center text-3xl font-bold", style: { color: '#D3790D', fontSize: '30px' }, children: ["Good Luck, ", firstName, "!"] })] }) }) }) })] }));
}
//# sourceMappingURL=lostTicket.js.map