import { KycProvider } from 'src/common/enum/kyc-provider.enum';
import { SupportedRegion } from 'src/common/enum/supported-region.enum';
import { Currency } from 'src/utils/enums/wallet.enum';
import {
  ProviderAirtimeCatalog,
  ProviderDataCatalog,
  ProviderUtilitiesCatalog,
} from '../interfaces/regional-provider.interface';

const region = SupportedRegion.NG;
const provider = KycProvider.FLUTTERWAVE;

export const FLUTTERWAVE_BILL_CATEGORY_CODES = {
  airtime: 'AIRTIME',
  data: 'MOBILEDATA',
  cable: 'CABLEBILLS',
  internet: 'INTSERVICE',
  utilities: 'UTILITYBILLS',
} as const;

const AIRTIME_BILLER_CODE = 'BIL099';
const AIRTIME_ITEM_CODE = 'AT099';
const AIRTIME_SERVICE_CODE = `${AIRTIME_BILLER_CODE}:${AIRTIME_ITEM_CODE}:AIRTIME`;

export const FLUTTERWAVE_AIRTIME_FALLBACK_CATALOG: ProviderAirtimeCatalog = {
  region,
  provider,
  source: 'CURATED_FALLBACK',
  message:
    'Live airtime discovery is unavailable. Returning VidalPay fallback airtime networks with Flutterwave reference codes for staging.',
  networks: [
    {
      id: 'mtn',
      code: 'MTN',
      title: 'MTN',
      description: 'Buy airtime for MTN numbers.',
      billerCode: AIRTIME_BILLER_CODE,
      itemCode: AIRTIME_ITEM_CODE,
      serviceCode: AIRTIME_SERVICE_CODE,
      currency: Currency.NGN,
      minAmount: 50,
      maxAmount: 50000,
      enabled: true,
    },
    {
      id: 'airtel',
      code: 'AIRTEL',
      title: 'Airtel',
      description: 'Top up Airtel numbers directly from your wallet.',
      billerCode: AIRTIME_BILLER_CODE,
      itemCode: AIRTIME_ITEM_CODE,
      serviceCode: AIRTIME_SERVICE_CODE,
      currency: Currency.NGN,
      minAmount: 50,
      maxAmount: 50000,
      enabled: true,
    },
    {
      id: 'glo',
      code: 'GLO',
      title: 'Glo',
      description: 'Buy airtime for Glo numbers.',
      billerCode: AIRTIME_BILLER_CODE,
      itemCode: AIRTIME_ITEM_CODE,
      serviceCode: AIRTIME_SERVICE_CODE,
      currency: Currency.NGN,
      minAmount: 50,
      maxAmount: 50000,
      enabled: true,
    },
    {
      id: '9mobile',
      code: '9MOBILE',
      title: '9mobile',
      description: 'Buy airtime for 9mobile numbers.',
      billerCode: AIRTIME_BILLER_CODE,
      itemCode: AIRTIME_ITEM_CODE,
      serviceCode: AIRTIME_SERVICE_CODE,
      currency: Currency.NGN,
      minAmount: 50,
      maxAmount: 50000,
      enabled: true,
    },
  ],
};

export const FLUTTERWAVE_DATA_FALLBACK_CATALOG: ProviderDataCatalog = {
  region,
  provider,
  source: 'CURATED_FALLBACK',
  message:
    'Live data-plan discovery is unavailable. Returning VidalPay fallback data plans with Flutterwave biller, item, and type values for staging.',
  networks: [
    {
      id: 'mtn',
      code: 'MTN',
      title: 'MTN',
      description: 'MTN mobile data bundles.',
      billerCode: 'BIL108',
      plans: [
        {
          id: 'mtn-750mb',
          code: 'MTN_750MB',
          title: '750MB',
          description: 'MTN 750MB data top-up service.',
          amount: 500,
          currency: Currency.NGN,
          serviceCode: 'BIL108:MD143:MTN 750MB data top-up service',
          billerCode: 'BIL108',
          itemCode: 'MD143',
          type: 'MTN 750MB data top-up service',
          enabled: true,
        },
        {
          id: 'mtn-1-5gb',
          code: 'MTN_1_5GB',
          title: '1.5GB',
          description: 'MTN 1.5 GB DATA BUNDLE.',
          amount: 1000,
          currency: Currency.NGN,
          serviceCode: 'BIL108:MD144:MTN 1.5 GB DATA BUNDLE',
          billerCode: 'BIL108',
          itemCode: 'MD144',
          type: 'MTN 1.5 GB DATA BUNDLE',
          enabled: true,
        },
      ],
    },
    {
      id: 'airtel',
      code: 'AIRTEL',
      title: 'Airtel',
      description: 'Airtel mobile data bundles.',
      billerCode: 'BIL110',
      plans: [
        {
          id: 'airtel-750mb',
          code: 'AIRTEL_750MB',
          title: '750MB',
          description: 'AIRTEL 750 MB data bundle.',
          amount: 500,
          currency: Currency.NGN,
          serviceCode: 'BIL110:MD139:AIRTEL 750 MB data bundle',
          billerCode: 'BIL110',
          itemCode: 'MD139',
          type: 'AIRTEL 750 MB data bundle',
          enabled: true,
        },
        {
          id: 'airtel-1-5gb',
          code: 'AIRTEL_1_5GB',
          title: '1.5GB',
          description: 'AIRTEL 1.5GB data bundle.',
          amount: 1000,
          currency: Currency.NGN,
          serviceCode: 'BIL110:MD140:AIRTEL 1.5GB data bundle',
          billerCode: 'BIL110',
          itemCode: 'MD140',
          type: 'AIRTEL 1.5GB data bundle',
          enabled: true,
        },
      ],
    },
    {
      id: 'glo',
      code: 'GLO',
      title: 'Glo',
      description: 'Glo mobile data bundles.',
      billerCode: 'BIL109',
      plans: [
        {
          id: 'glo-920mb',
          code: 'GLO_920MB',
          title: '920MB',
          description: 'GLO 920 MB DATA BUNDLE.',
          amount: 500,
          currency: Currency.NGN,
          serviceCode: 'BIL109:MD148:GLO 920 MB DATA BUNDLE',
          billerCode: 'BIL109',
          itemCode: 'MD148',
          type: 'GLO 920 MB DATA BUNDLE',
          enabled: true,
        },
        {
          id: 'glo-1-8gb',
          code: 'GLO_1_8GB',
          title: '1.8GB',
          description: 'GLO 1.8GB data purchase.',
          amount: 1000,
          currency: Currency.NGN,
          serviceCode: 'BIL109:MD149:GLO 1.8GB data purchase',
          billerCode: 'BIL109',
          itemCode: 'MD149',
          type: 'GLO 1.8GB data purchase',
          enabled: true,
        },
      ],
    },
    {
      id: '9mobile',
      code: '9MOBILE',
      title: '9mobile',
      description: '9mobile data bundles.',
      billerCode: 'BIL111',
      plans: [
        {
          id: '9mobile-1-5gb',
          code: 'NINEMOBILE_1_5GB',
          title: '1.5GB',
          description: '9MOBILE 1.5GB data bundle.',
          amount: 1000,
          currency: Currency.NGN,
          serviceCode: 'BIL111:MD154:9MOBILE 1.5GB data bundle',
          billerCode: 'BIL111',
          itemCode: 'MD154',
          type: '9MOBILE 1.5GB data bundle',
          enabled: true,
        },
        {
          id: '9mobile-4-5gb',
          code: 'NINEMOBILE_4_5GB',
          title: '4.5GB',
          description: '9MOBILE 4.5GB data bundle.',
          amount: 2000,
          currency: Currency.NGN,
          serviceCode: 'BIL111:MD155:9MOBILE 4.5GB data bundle',
          billerCode: 'BIL111',
          itemCode: 'MD155',
          type: '9MOBILE 4.5GB data bundle',
          enabled: true,
        },
      ],
    },
  ],
};

export const FLUTTERWAVE_UTILITIES_FALLBACK_CATALOG: ProviderUtilitiesCatalog = {
  region,
  provider,
  source: 'CURATED_FALLBACK',
  message:
    'Live utility discovery is unavailable. Returning VidalPay fallback utilities with Flutterwave reference codes for staging. Internet providers still depend on live discovery.',
  categories: [
    {
      id: 'electricity',
      code: 'ELECTRICITY',
      title: 'Electricity',
      description: 'Pay prepaid and postpaid electricity bills.',
      providers: [
        {
          id: 'eko-electric',
          code: 'EKEDC',
          title: 'Eko Electric',
          description: 'Pay for Eko Disco prepaid and postpaid electricity.',
          billerCode: 'BIL112',
          itemCode: 'UB157',
          type: 'POWER',
          requiresValidation: true,
          customerReferenceLabel: 'Meter Number',
          currency: Currency.NGN,
          enabled: true,
          items: [
            {
              id: 'eko-prepaid',
              code: 'EKEDC_PREPAID',
              title: 'Eko Prepaid',
              description: 'Prepaid Eko Disco meter payment.',
              amount: null,
              currency: Currency.NGN,
              serviceCode: 'BIL112:UB157:EKO PREPAID',
              billerCode: 'BIL112',
              itemCode: 'UB157',
              type: 'EKO PREPAID',
              requiresValidation: true,
              customerReferenceLabel: 'Meter Number',
              enabled: true,
            },
            {
              id: 'eko-postpaid',
              code: 'EKEDC_POSTPAID',
              title: 'Eko Postpaid',
              description: 'Postpaid Eko Disco account payment.',
              amount: null,
              currency: Currency.NGN,
              serviceCode: 'BIL112:UB158:EKO POSTPAID',
              billerCode: 'BIL112',
              itemCode: 'UB158',
              type: 'EKO POSTPAID',
              requiresValidation: true,
              customerReferenceLabel: 'Meter Number',
              enabled: true,
            },
          ],
        },
      ],
    },
    {
      id: 'tv',
      code: 'CABLE',
      title: 'Cable & TV',
      description: 'Renew cable and satellite subscriptions.',
      providers: [
        {
          id: 'dstv',
          code: 'DSTV',
          title: 'DStv',
          description: 'Recharge DStv decoder and smartcard subscriptions.',
          billerCode: 'BIL119',
          itemCode: 'CB141',
          type: 'CABLE',
          requiresValidation: true,
          customerReferenceLabel: 'Smartcard Number',
          currency: Currency.NGN,
          enabled: true,
          items: [
            {
              id: 'dstv-cb140',
              code: 'DSTV_PAYMENT_CB140',
              title: 'DStv Payment',
              description: 'DStv package payment option.',
              amount: null,
              currency: Currency.NGN,
              serviceCode: 'BIL119:CB140:DSTV Payment',
              billerCode: 'BIL119',
              itemCode: 'CB140',
              type: 'DSTV Payment',
              requiresValidation: true,
              customerReferenceLabel: 'Smartcard Number',
              enabled: true,
            },
            {
              id: 'dstv-cb141',
              code: 'DSTV_PAYMENT_CB141',
              title: 'DStv Payment Alt',
              description: 'Alternate DStv package payment option.',
              amount: null,
              currency: Currency.NGN,
              serviceCode: 'BIL119:CB141:DSTV Payment',
              billerCode: 'BIL119',
              itemCode: 'CB141',
              type: 'DSTV Payment',
              requiresValidation: true,
              customerReferenceLabel: 'Smartcard Number',
              enabled: true,
            },
          ],
        },
      ],
    },
    {
      id: 'internet',
      code: 'INTERNET',
      title: 'Internet / Broadband',
      description: 'Handle broadband and internet account renewals.',
      providers: [],
    },
  ],
};
