import { Currency } from 'src/utils/enums/wallet.enum';
import {
  ProviderAirtimeCatalog,
  ProviderDataCatalog,
  ProviderUtilitiesCatalog,
} from '../interfaces/regional-provider.interface';
import { KycProvider } from 'src/common/enum/kyc-provider.enum';
import { SupportedRegion } from 'src/common/enum/supported-region.enum';

const region = SupportedRegion.NG;
const provider = KycProvider.FLUTTERWAVE;

export const FLUTTERWAVE_BILL_CATEGORY_CODES = {
  airtime: 'AIRTIME',
  data: 'MOBILEDATA',
  cable: 'CABLEBILLS',
  internet: 'INTSERVICE',
  utilities: 'UTILITYBILLS',
} as const;

export const FLUTTERWAVE_AIRTIME_FALLBACK_CATALOG: ProviderAirtimeCatalog = {
  region,
  provider,
  source: 'CURATED_FALLBACK',
  message:
    'Live airtime discovery is unavailable. The backend is returning a curated fallback list until provider discovery is restored.',
  networks: [
    {
      id: 'mtn',
      code: 'MTN',
      title: 'MTN',
      description: 'Buy airtime for MTN numbers.',
      billerCode: null,
      itemCode: null,
      serviceCode: null,
      currency: Currency.NGN,
      minAmount: 50,
      maxAmount: 50000,
      enabled: false,
    },
    {
      id: 'airtel',
      code: 'AIRTEL',
      title: 'Airtel',
      description: 'Top up Airtel numbers directly from your wallet.',
      billerCode: null,
      itemCode: null,
      serviceCode: null,
      currency: Currency.NGN,
      minAmount: 50,
      maxAmount: 50000,
      enabled: false,
    },
    {
      id: 'glo',
      code: 'GLO',
      title: 'Glo',
      description: 'Buy airtime for Glo numbers.',
      billerCode: null,
      itemCode: null,
      serviceCode: null,
      currency: Currency.NGN,
      minAmount: 50,
      maxAmount: 50000,
      enabled: false,
    },
    {
      id: '9mobile',
      code: '9MOBILE',
      title: '9mobile',
      description: 'Buy airtime for 9mobile numbers.',
      billerCode: null,
      itemCode: null,
      serviceCode: null,
      currency: Currency.NGN,
      minAmount: 50,
      maxAmount: 50000,
      enabled: false,
    },
  ],
};

export const FLUTTERWAVE_DATA_FALLBACK_CATALOG: ProviderDataCatalog = {
  region,
  provider,
  source: 'CURATED_FALLBACK',
  message:
    'Live data-plan discovery is unavailable. The backend is returning a curated fallback list until provider discovery is restored.',
  networks: [
    {
      id: 'mtn',
      code: 'MTN',
      title: 'MTN',
      description: 'MTN mobile data bundles.',
      billerCode: null,
      plans: [
        {
          id: 'mtn-500mb-daily',
          code: 'MTN_500MB_DAILY',
          title: '500MB Daily',
          description: 'Short-term top-up for light usage.',
          amount: 500,
          currency: Currency.NGN,
          serviceCode: null,
          billerCode: null,
          itemCode: null,
          type: null,
          enabled: false,
        },
        {
          id: 'mtn-1gb-weekly',
          code: 'MTN_1GB_WEEKLY',
          title: '1GB Weekly',
          description: 'A steady weekly bundle for browsing.',
          amount: 1000,
          currency: Currency.NGN,
          serviceCode: null,
          billerCode: null,
          itemCode: null,
          type: null,
          enabled: false,
        },
      ],
    },
    {
      id: 'airtel',
      code: 'AIRTEL',
      title: 'Airtel',
      description: 'Airtel mobile data bundles.',
      billerCode: null,
      plans: [
        {
          id: 'airtel-500mb-daily',
          code: 'AIRTEL_500MB_DAILY',
          title: '500MB Daily',
          description: 'Short-term bundle for Airtel numbers.',
          amount: 500,
          currency: Currency.NGN,
          serviceCode: null,
          billerCode: null,
          itemCode: null,
          type: null,
          enabled: false,
        },
        {
          id: 'airtel-1gb-weekly',
          code: 'AIRTEL_1GB_WEEKLY',
          title: '1GB Weekly',
          description: 'A simple weekly data option.',
          amount: 1000,
          currency: Currency.NGN,
          serviceCode: null,
          billerCode: null,
          itemCode: null,
          type: null,
          enabled: false,
        },
      ],
    },
    {
      id: 'glo',
      code: 'GLO',
      title: 'Glo',
      description: 'Glo mobile data bundles.',
      billerCode: null,
      plans: [
        {
          id: 'glo-500mb-daily',
          code: 'GLO_500MB_DAILY',
          title: '500MB Daily',
          description: 'Entry bundle for day-to-day browsing.',
          amount: 500,
          currency: Currency.NGN,
          serviceCode: null,
          billerCode: null,
          itemCode: null,
          type: null,
          enabled: false,
        },
        {
          id: 'glo-1gb-weekly',
          code: 'GLO_1GB_WEEKLY',
          title: '1GB Weekly',
          description: 'Mid-range bundle for one week.',
          amount: 1000,
          currency: Currency.NGN,
          serviceCode: null,
          billerCode: null,
          itemCode: null,
          type: null,
          enabled: false,
        },
      ],
    },
    {
      id: '9mobile',
      code: '9MOBILE',
      title: '9mobile',
      description: '9mobile data bundles.',
      billerCode: null,
      plans: [
        {
          id: '9mobile-500mb-daily',
          code: '9MOBILE_500MB_DAILY',
          title: '500MB Daily',
          description: 'Daily bundle for 9mobile users.',
          amount: 500,
          currency: Currency.NGN,
          serviceCode: null,
          billerCode: null,
          itemCode: null,
          type: null,
          enabled: false,
        },
        {
          id: '9mobile-1gb-weekly',
          code: '9MOBILE_1GB_WEEKLY',
          title: '1GB Weekly',
          description: 'Weekly option for browsing and chat.',
          amount: 1000,
          currency: Currency.NGN,
          serviceCode: null,
          billerCode: null,
          itemCode: null,
          type: null,
          enabled: false,
        },
      ],
    },
  ],
};

export const FLUTTERWAVE_UTILITIES_FALLBACK_CATALOG: ProviderUtilitiesCatalog = {
  region,
  provider,
  source: 'CURATED_FALLBACK',
  message:
    'Live utility discovery is unavailable. The backend is returning a curated fallback list until provider discovery is restored.',
  categories: [
    {
      id: 'electricity',
      code: 'ELECTRICITY',
      title: 'Electricity',
      description: 'Pay prepaid and postpaid electricity bills.',
      providers: [
        {
          id: 'ikeja-electric',
          code: 'IKEDC',
          title: 'Ikeja Electric',
          description: 'Pay for IKEDC electricity services.',
          billerCode: null,
          itemCode: null,
          type: 'POWER',
          requiresValidation: true,
          customerReferenceLabel: 'Meter Number',
          currency: Currency.NGN,
          enabled: false,
          items: [],
        },
        {
          id: 'eko-electric',
          code: 'EKEDC',
          title: 'Eko Electric',
          description: 'Manage EKEDC prepaid or postpaid accounts.',
          billerCode: null,
          itemCode: null,
          type: 'POWER',
          requiresValidation: true,
          customerReferenceLabel: 'Meter Number',
          currency: Currency.NGN,
          enabled: false,
          items: [],
        },
        {
          id: 'abuja-electric',
          code: 'AEDC',
          title: 'Abuja Electric',
          description: 'Fund AEDC electricity meters and accounts.',
          billerCode: null,
          itemCode: null,
          type: 'POWER',
          requiresValidation: true,
          customerReferenceLabel: 'Meter Number',
          currency: Currency.NGN,
          enabled: false,
          items: [],
        },
      ],
    },
    {
      id: 'tv',
      code: 'CABLE',
      title: 'Cable & TV',
      description: 'Renew cable and satellite subscriptions.',
      providers: [
        {
          id: 'dstv',
          code: 'DSTV',
          title: 'DStv',
          description: 'Recharge your DStv smartcard.',
          billerCode: null,
          itemCode: null,
          type: 'CABLE',
          requiresValidation: true,
          customerReferenceLabel: 'Smartcard Number',
          currency: Currency.NGN,
          enabled: false,
          items: [],
        },
        {
          id: 'gotv',
          code: 'GOTV',
          title: 'GOtv',
          description: 'Top up GOtv plans and subscriptions.',
          billerCode: null,
          itemCode: null,
          type: 'CABLE',
          requiresValidation: true,
          customerReferenceLabel: 'Decoder Number',
          currency: Currency.NGN,
          enabled: false,
          items: [],
        },
        {
          id: 'startimes',
          code: 'STARTIMES',
          title: 'StarTimes',
          description: 'Pay for StarTimes subscriptions.',
          billerCode: null,
          itemCode: null,
          type: 'CABLE',
          requiresValidation: true,
          customerReferenceLabel: 'Smartcard Number',
          currency: Currency.NGN,
          enabled: false,
          items: [],
        },
      ],
    },
    {
      id: 'internet',
      code: 'INTERNET',
      title: 'Internet / Broadband',
      description: 'Handle broadband and internet account renewals.',
      providers: [
        {
          id: 'ipnx',
          code: 'IPNX',
          title: 'IPNX',
          description: 'Pay broadband account renewals.',
          billerCode: null,
          itemCode: null,
          type: 'INTERNET',
          requiresValidation: true,
          customerReferenceLabel: 'Account Number',
          currency: Currency.NGN,
          enabled: false,
          items: [],
        },
      ],
    },
  ],
};
