"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const jsx_runtime_1 = require("react/jsx-runtime");
const components_1 = require("@react-email/components");
const EmailLayout = ({ children }) => {
    return ((0, jsx_runtime_1.jsxs)(components_1.Html, { lang: "en", title: "Lottonownow", style: {
            fontFamily: 'Exo, Verdana, sans-serif',
            padding: '0',
            margin: '0',
            backgroundColor: '#f8f8f8',
        }, children: [(0, jsx_runtime_1.jsx)(components_1.Font, { fontFamily: "Exo", fallbackFontFamily: "Verdana", fontWeight: 400, fontStyle: "normal" }), (0, jsx_runtime_1.jsxs)(components_1.Tailwind, { children: [(0, jsx_runtime_1.jsx)(components_1.Head, { children: (0, jsx_runtime_1.jsx)("link", { href: "https://fonts.googleapis.com/css2?family=Exo:wght@400;500;700&display=swap", rel: "stylesheet" }) }), (0, jsx_runtime_1.jsxs)(components_1.Container, { className: "w-full", children: [(0, jsx_runtime_1.jsx)(components_1.Img, { src: "https://res.cloudinary.com/dlhjvo4tz/image/upload/v1734509114/Picture2_1_2_vij7bz.svg", alt: "layout", className: "w-full h-1/2 object-cover " }), (0, jsx_runtime_1.jsx)(components_1.Section, { className: "p-4 font-Exo text-sm bg-white my-5", children: children })] }), (0, jsx_runtime_1.jsxs)(components_1.Container, { className: "bg-white w-full p-4", children: [(0, jsx_runtime_1.jsxs)("div", { className: "w-full flex flex-col md:flex-row jusify-between md:items-center items:start", children: [(0, jsx_runtime_1.jsxs)("div", { className: "w-full text-sm", children: [(0, jsx_runtime_1.jsx)(components_1.Text, { children: " Want to reach out to us?" }), (0, jsx_runtime_1.jsx)(components_1.Text, { className: "font-Exo text-primary", children: "Contact us" }), (0, jsx_runtime_1.jsx)(components_1.Link, { href: "mailto:support@vidalpay.com", className: "text-primary no-underline ", children: "support@vidalpay.com" }), (0, jsx_runtime_1.jsx)(components_1.Text, { children: (0, jsx_runtime_1.jsx)(components_1.Link, { href: "tel:+2348038274270", className: "text-primary no-underline ", children: "+234-803-827-4270" }) }), (0, jsx_runtime_1.jsx)(components_1.Text, { children: (0, jsx_runtime_1.jsx)(components_1.Link, { href: "https://www.vidalpay.com", className: "text-primary no-underline ", children: "www.vidalpay.com" }) })] }), (0, jsx_runtime_1.jsx)("div", { children: (0, jsx_runtime_1.jsxs)("div", { className: "w-full flex space-x-2 md:mt-20 my-10", children: [(0, jsx_runtime_1.jsx)(components_1.Link, { href: "https://www.instagram.com/vidalpay", children: (0, jsx_runtime_1.jsx)(components_1.Img, { src: "https://hervest-users.s3.eu-west-1.amazonaws.com/instagram.png", alt: "instagram", className: "w-[32px] h-[32px] mx-2 " }) }), (0, jsx_runtime_1.jsx)(components_1.Link, { href: "https://x.com/vidalpay", children: (0, jsx_runtime_1.jsx)(components_1.Img, { src: "https://res.cloudinary.com/dlhjvo4tz/image/upload/v1721545013/twitter_hkdxk5.png", alt: "Twitter", className: "w-[32px] h-[32px] mx-2 " }) }), (0, jsx_runtime_1.jsx)(components_1.Link, { href: "https://www.facebook.com/profile.php?id=61575680710313", children: (0, jsx_runtime_1.jsx)(components_1.Img, { src: "https://res.cloudinary.com/dlhjvo4tz/image/upload/v1721545012/facebook_xykbuh.png", alt: "Facebook", className: "w-[32px] h-[32px] mx-2 " }) })] }) })] }), (0, jsx_runtime_1.jsxs)(components_1.Section, { style: {
                                    fontFamily: 'Exo',
                                }, className: "text-gray-400 text-xs", children: [(0, jsx_runtime_1.jsx)(components_1.Hr, { className: "border-t border-gray-200" }), (0, jsx_runtime_1.jsx)(components_1.Text, { children: "This email is automatically generated and does not require a response." })] })] })] })] }));
};
exports.default = EmailLayout;
//# sourceMappingURL=emailLayout.js.map