export enum AdminUserActionType {
  SUSPEND = 'SUSPEND',
  REACTIVATE = 'REACTIVATE',
  ROLE_CHANGE = 'ROLE_CHANGE',
  KYC_APPROVE = 'KYC_APPROVE',
  KYC_REJECT = 'KYC_REJECT',
  KYC_REQUIRE_ACTION = 'KYC_REQUIRE_ACTION',
}
