"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = AccountDeactivatedNotification;
const jsx_runtime_1 = require("react/jsx-runtime");
const components_1 = require("@react-email/components");
const emailLayout_1 = require("../components/emailLayout");
const config_1 = require("../../src/utils/config");
function AccountDeactivatedNotification({ userName }) {
    return ((0, jsx_runtime_1.jsxs)(components_1.Html, { children: [(0, jsx_runtime_1.jsxs)(components_1.Preview, { children: [userName, "! We are sorry to see you go!"] }), (0, jsx_runtime_1.jsx)(components_1.Tailwind, { children: (0, jsx_runtime_1.jsx)(components_1.Body, { children: (0, jsx_runtime_1.jsx)(emailLayout_1.default, { children: (0, jsx_runtime_1.jsxs)(components_1.Row, { children: [(0, jsx_runtime_1.jsx)("h4", { className: "text-xl font-semibold", style: { fontSize: '25px' } }), (0, jsx_runtime_1.jsxs)(components_1.Text, { children: ["Hi ", userName, ","] }), (0, jsx_runtime_1.jsx)(components_1.Text, { className: "text-justify", children: "We noticed that you\u2019ve decided to deactivate your account, and while we\u2019re sad to see you go, we completely understand. However, we\u2019d love to have you back!" }), (0, jsx_runtime_1.jsx)(components_1.Text, { className: "text-justify", children: "The good news is, you have 30 days to change your mind and reactivate your account. Simply click the \u201CReactivate Account\u201D button to restore access. It\u2019s quick, easy, and we\u2019d be thrilled to welcome you back!" }), (0, jsx_runtime_1.jsx)(components_1.Text, { className: "text-justify", children: "Here\u2019s what you need to know:" }), (0, jsx_runtime_1.jsxs)("ul", { children: [(0, jsx_runtime_1.jsx)("li", { children: "Any funds in your wallet will remain available for the next 30 days. Be sure to withdraw them or use them before your account is permanently deactivated." }), (0, jsx_runtime_1.jsx)("li", { children: "After 30 days, your account and all associated data will be permanently deactivated and no longer accessible." })] }), (0, jsx_runtime_1.jsx)(components_1.Button, { href: `${config_1.CONFIG_VARIABLES.APP_URL}/login`, className: "text-center bg-black text-white text-2xl my-5 font-bold rounded-xl no-underline px-8 py-4", children: "REACTIVATE ACCOUNT" }), (0, jsx_runtime_1.jsxs)(components_1.Text, { className: "text-justify", children: ["If there\u2019s anything we can do to make your experience better or if you have any questions, please don\u2019t hesitate to reach out to us at ", config_1.CONFIG_VARIABLES.SUPPORT_EMAIL, " or", ' ', config_1.CONFIG_VARIABLES.SUPPORT_PHONE, ". We\u2019re here to help!", ' '] })] }) }) }) })] }));
}
//# sourceMappingURL=accountDeactivated.js.map