export enum DisputeKind {
  TRANSACTION_DISPUTE = 'TRANSACTION_DISPUTE',
  CHARGEBACK = 'CHARGEBACK',
}

export enum DisputeReason {
  CARD_NOT_PRESENT = 'CARD_NOT_PRESENT',
  CASH_NOT_RECEIVED = 'CASH_NOT_RECEIVED',
  DUPLICATE = 'DUPLICATE',
  INCORRECT_AMOUNT = 'INCORRECT_AMOUNT',
  MERCHANDISE_NOT_RECEIVED = 'MERCHANDISE_NOT_RECEIVED',
  SERVICE_NOT_PROVIDED = 'SERVICE_NOT_PROVIDED',
  UNRECOGNIZED = 'UNRECOGNIZED',
  OTHER = 'OTHER',
}

export enum DisputeStatus {
  PENDING_PROVIDER = 'PENDING_PROVIDER',
  NEEDS_INFORMATION = 'NEEDS_INFORMATION',
  UNDER_REVIEW = 'UNDER_REVIEW',
  WON = 'WON',
  LOST = 'LOST',
  WITHDRAWN = 'WITHDRAWN',
  EXPIRED = 'EXPIRED',
}

export enum DisputeEventSource {
  USER = 'USER',
  ADMIN = 'ADMIN',
  PROVIDER = 'PROVIDER',
  SYSTEM = 'SYSTEM',
}

export enum RefundStatus {
  PENDING_REVIEW = 'PENDING_REVIEW',
  PENDING_PROVIDER = 'PENDING_PROVIDER',
  APPROVED = 'APPROVED',
  COMPLETED = 'COMPLETED',
  REJECTED = 'REJECTED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

export enum EvidenceType {
  RECEIPT = 'RECEIPT',
  CORRESPONDENCE = 'CORRESPONDENCE',
  DELIVERY_PROOF = 'DELIVERY_PROOF',
  IDENTITY_DOCUMENT = 'IDENTITY_DOCUMENT',
  OTHER = 'OTHER',
}
